spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.uvajfkklrfudnkowkrzw
    password: ZY^ml64dpZmW
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple
    user: postgres.uvajfkklrfudnkowkrzw
    password: ZY^ml64dpZmW
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://uvajfkklrfudnkowkrzw.supabase.co/auth/v1/.well-known/jwks.json
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
server:
  port: 8080
  servlet:
    context-path: /finplan/api/v1
logging:
  level:
    org.hibernate.SQL: DEBUG
supabase:
  auth:
    audience: "authenticated"
  url: https://uvajfkklrfudnkowkrzw.supabase.co
  service-role-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YWpma2tscmZ1ZG5rb3drcnp3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzY0MDMyOCwiZXhwIjoyMDgzMjE2MzI4fQ.18R0JbEtj7-zv7rbdj41Hk0yJXnSKn7WhlLLs-JK4Js