spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.uvajfkklrfudnkowkrzw
    password: ZY^ml64dpZmW
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple
    user: postgres.uvajfkklrfudnkowkrzw
    password: ZY^ml64dpZmW

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /finplan/api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG